# Generated by Django 3.2.9 on 2022-12-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_agent_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='can_change_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='can_change_vacancy',
            field=models.BooleanField(default=False),
        ),
    ]
