# Generated by Django 3.2.9 on 2022-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number_of_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
