# Generated by Django 3.2.9 on 2022-12-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_apartment_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='lattitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
