# Generated by Django 3.2.9 on 2022-12-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_auto_20221216_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
