# Generated by Django 3.2.9 on 2022-12-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default='45aca6', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
